drop table if exists ACCOUNT;

CREATE TABLE ACCOUNT(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   RETAILER_ID INTEGER NOT NULL,
   CLIENT_ID INTEGER NOT NULL,
   USER TEXT NOT NULL,
   PASSWORD TEXT NOT NULL,
   COMPANY TEXT,
   FOREIGN KEY (RETAILER_ID)
      REFERENCES RETAILER (ID),
   FOREIGN KEY (CLIENT_ID)
      REFERENCES CLIENT (ID),
   UNIQUE(CLIENT_ID, RETAILER_ID111)
);
