drop table if exists ACCOUNT;

CREATE TABLE ACCOUNT(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   RETAILER_ID INTEGER NOT NULL,
   HOLDING_ID INTEGER NOT NULL,
   USER TEXT NOT NULL,
   PASSWORD TEXT NOT NULL,
   COMPANY TEXT,
   FOREIGN KEY (RETAILER_ID)
      REFERENCES RETAILER (ID),
   FOREIGN KEY (HOLDING_ID)
      REFERENCES HOLDING (ID),
   UNIQUE(RETAILER_ID, HOLDING_ID)
);